baseURL = "https://whiley.github.io/WhileyOrg/"
languageCode = "en-nz"
title = "Whiley Homepage"
googleAnalytics = "UA-5582165-5"
paginate = 10
enableRobotsTXT = true
summaryLength = 30
pygmentsStyle = "manni"

[permalinks]
blog = "/:year/:month/:day/:title/"
