baseURL = "https://whiley.org"
languageCode = "en-nz"
title = "Whiley Homepage"
googleAnalytics = "UA-5582165-5"
paginate = 10
enableRobotsTXT = true
summaryLength = 30
pygmentsStyle = "manni"

[permalinks]
blog = "/blog//:year/:month/:day/:title/"
