baseURL = "https://whiley.org/"
languageCode = "en-nz"
title = "Whiley Homepage"
googleAnalytics = "G-595YEBLV7C"
paginate = 10
enableRobotsTXT = true
summaryLength = 30

[permalinks]
news = "/:year/:month/:day/:title/"

[markup]

[markup.goldmark.renderer]
unsafe=true

[markup.highlight]
noClasses=false
